#!/bin/bash
source ~/.dotfiles/colors.sh
ASPELL=$(which aspell)
if [ $? -ne 0 ]; then
    echo -e "${red}Aspell not installed - unable to check spelling${default}" >&2
    exit
else
    WORDS=$($ASPELL list < "$1")
fi
if [ -n "$WORDS" ]; then
    echo -e "${yellow}\tPossible spelling errors found in commit message. Use git commit --amend to change the message.\n\tPossible mispelled words: " $WORDS ".${default}" >&2
fi
