#!/bin/bash

default="\033[39m"
black="\033[30m"
red="\033[0;31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
magenta="\033[35m"
cyan="\033[36m"
light_gray="\033[37m"
dark_gray="\033[90m"
light_red="\033[91m"
light_green="\033[92m"
light_yellow="\033[93m"
light_blue="\033[94m"
light_magenta="\033[95m"
light_cyan="\033[96m"
white="\033[97m"

echo -e "${green}-- Lancement du script --${default}"

echo -e "${yellow}Nettoyage du dossier /var/www/html/monitoring${default}"
rm -rf  /var/www/html/monitoring/*

echo -e "${yellow}Récupération de l'archive du dépôt et extraction dans /var/www/html/monitoring/${default}"
git archive main | tar -x -C /var/www/html/monitoring

echo -e "${yellow}Supression du README${default}"
rm /var/www/html/monitoring/README.md

echo -e "${green}-- Fin du script --${default}"
