#!/bin/bash
# Copyright (C) 2014 Julien Bonjean 
# Copyright (C) 2014 Alexander Keller 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see .

ICON=""
OUT_IP=$(dig +short myip.opendns.com @208.67.220.220)
if [[ ! -z "$OUT_IP" ]]; then
    COLOR=' foreground="#FFD300"'
fi

echo "<span$COLOR> $ICON $OUT_IP</span>" # full text
