#!/usr/bin/env bash
# Be sure to change the WLAN interface
SSID=$(/usr/sbin/iw dev wlp0s20f3 link | grep SSID | cut -d " " -f 2-) 
if [[ ! -z "$SSID" ]]; then
   COLOR=' foreground="#FFFFFF"'
fi
echo "<span$COLOR>  $SSID</span>"
