#!/usr/bin/env bash
ICON=""
BG_COLOR=""
vpn_status=`sudo wg`
if [ ! -z "$vpn_status" ]; then
    COLOR=' foreground="#E53935"'
    ICON=""
else
    ICON="toto"
fi
echo "<span$COLOR>$ICON VPN</span>"
