source ~/dotfiles/nvim/plugins.vim
source ~/dotfiles/nvim/theme.vim 
source ~/dotfiles/nvim/config.vim
source ~/dotfiles/nvim/php.vim
source ~/dotfiles/nvim/coc.vim
source ~/dotfiles/nvim/term.vim
source ~/dotfiles/nvim/database.vim
source ~/dotfiles/nvim/shortcuts.vim
source ~/dotfiles/nvim/leaders.vim
source ~/dotfiles/nvim/git.vim
source ~/dotfiles/nvim/functions.vim
